Made our Flask project a proper Python module (__init__.py) so we can import from it.
X278-2016/team-12 pull request #24
Opened 2016-12-04 02:35 UTC by hstall2529

- Made directory structure less flat to allow for modularization
- Renamed server file to make the flask app a proper app
- To start the server now, run  `$ python runserver.py`.

2016-12-04 02:42 UTC, hoyosjs requested changes

2016-12-04 02:42 UTC, hoyosjs commented on makerspace_backend/runserver.py
> +app.run(debug=True)
You sure we want to make it debug true by default? And do we have all the dependencies here?

2016-12-04 02:42 UTC, hoyosjs commented on makerspace_backend/runserver.py
> +app.run(debug=True)
We could make the debug false by default and then set the true as a -d flag in this. We should also wrap this with a 
```python
if __name__ == '__main__':
    ...
```

2016-12-04 18:37 UTC, hstall2529 commented on makerspace_backend/runserver.py
> +app.run(debug=True)
Changes made

2016-12-06 12:16 UTC, hoyosjs approved these changes

2016-12-06 12:16 UTC, merged